/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as Agent_studioRouteImport } from './routes/agent_studio'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemplateUseTemplateIdRouteImport } from './routes/template-use.$templateId'
import { Route as InviteCodeRouteImport } from './routes/invite.$code'
import { Route as CanvasIdRouteImport } from './routes/canvas.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const Agent_studioRoute = Agent_studioRouteImport.update({
  id: '/agent_studio',
  path: '/agent_studio',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplateUseTemplateIdRoute = TemplateUseTemplateIdRouteImport.update({
  id: '/template-use/$templateId',
  path: '/template-use/$templateId',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteCodeRoute = InviteCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => InviteRoute,
} as any)
const CanvasIdRoute = CanvasIdRouteImport.update({
  id: '/canvas/$id',
  path: '/canvas/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent_studio': typeof Agent_studioRoute
  '/assets': typeof AssetsRoute
  '/invite': typeof InviteRouteWithChildren
  '/knowledge': typeof KnowledgeRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/templates': typeof TemplatesRoute
  '/terms': typeof TermsRoute
  '/canvas/$id': typeof CanvasIdRoute
  '/invite/$code': typeof InviteCodeRoute
  '/template-use/$templateId': typeof TemplateUseTemplateIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent_studio': typeof Agent_studioRoute
  '/assets': typeof AssetsRoute
  '/invite': typeof InviteRouteWithChildren
  '/knowledge': typeof KnowledgeRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/templates': typeof TemplatesRoute
  '/terms': typeof TermsRoute
  '/canvas/$id': typeof CanvasIdRoute
  '/invite/$code': typeof InviteCodeRoute
  '/template-use/$templateId': typeof TemplateUseTemplateIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent_studio': typeof Agent_studioRoute
  '/assets': typeof AssetsRoute
  '/invite': typeof InviteRouteWithChildren
  '/knowledge': typeof KnowledgeRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/templates': typeof TemplatesRoute
  '/terms': typeof TermsRoute
  '/canvas/$id': typeof CanvasIdRoute
  '/invite/$code': typeof InviteCodeRoute
  '/template-use/$templateId': typeof TemplateUseTemplateIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent_studio'
    | '/assets'
    | '/invite'
    | '/knowledge'
    | '/pricing'
    | '/privacy'
    | '/templates'
    | '/terms'
    | '/canvas/$id'
    | '/invite/$code'
    | '/template-use/$templateId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent_studio'
    | '/assets'
    | '/invite'
    | '/knowledge'
    | '/pricing'
    | '/privacy'
    | '/templates'
    | '/terms'
    | '/canvas/$id'
    | '/invite/$code'
    | '/template-use/$templateId'
  id:
    | '__root__'
    | '/'
    | '/agent_studio'
    | '/assets'
    | '/invite'
    | '/knowledge'
    | '/pricing'
    | '/privacy'
    | '/templates'
    | '/terms'
    | '/canvas/$id'
    | '/invite/$code'
    | '/template-use/$templateId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Agent_studioRoute: typeof Agent_studioRoute
  AssetsRoute: typeof AssetsRoute
  InviteRoute: typeof InviteRouteWithChildren
  KnowledgeRoute: typeof KnowledgeRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  TemplatesRoute: typeof TemplatesRoute
  TermsRoute: typeof TermsRoute
  CanvasIdRoute: typeof CanvasIdRoute
  TemplateUseTemplateIdRoute: typeof TemplateUseTemplateIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent_studio': {
      id: '/agent_studio'
      path: '/agent_studio'
      fullPath: '/agent_studio'
      preLoaderRoute: typeof Agent_studioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/template-use/$templateId': {
      id: '/template-use/$templateId'
      path: '/template-use/$templateId'
      fullPath: '/template-use/$templateId'
      preLoaderRoute: typeof TemplateUseTemplateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$code': {
      id: '/invite/$code'
      path: '/$code'
      fullPath: '/invite/$code'
      preLoaderRoute: typeof InviteCodeRouteImport
      parentRoute: typeof InviteRoute
    }
    '/canvas/$id': {
      id: '/canvas/$id'
      path: '/canvas/$id'
      fullPath: '/canvas/$id'
      preLoaderRoute: typeof CanvasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface InviteRouteChildren {
  InviteCodeRoute: typeof InviteCodeRoute
}

const InviteRouteChildren: InviteRouteChildren = {
  InviteCodeRoute: InviteCodeRoute,
}

const InviteRouteWithChildren =
  InviteRoute._addFileChildren(InviteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Agent_studioRoute: Agent_studioRoute,
  AssetsRoute: AssetsRoute,
  InviteRoute: InviteRouteWithChildren,
  KnowledgeRoute: KnowledgeRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  TemplatesRoute: TemplatesRoute,
  TermsRoute: TermsRoute,
  CanvasIdRoute: CanvasIdRoute,
  TemplateUseTemplateIdRoute: TemplateUseTemplateIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
